### ISSUE TITLE
Crossing Markings pictograms have disappeared from the dropdown list

### ISSUE THREAD

**Issue by Snowysauce** [openstreetmap/iD#10301]
### How to reproduce the issue?

1. Select a crossing feature (e.g., highway=crossing) on the map.
2. Select the "Crossing Markings" dropdown list. The pictograms for each crossing style that were once there are no longer present, despite a place still clearly existing for their display.

### Which deployed environments do you see the issue in?

Released version at openstreetmap.org/edit

### What version numbers does this issue effect?

2.29.0

### Which browsers are you seeing this problem on?

Chrome, Microsoft Edge, Pale Moon (Firefox derivative)

**Comment by k-yle** [comment]
This was fixed in 3de2840ac3b5849bfdecd5f0b9b9a83be262e7e2 but the changes haven't been released yet

**Comment by tjhorner** [comment]
Has the change been deployed? The icons are still missing for me.

**Comment by tordans** [comment]
No, not deployed yet. But close AFAIK.

**Comment by tjhorner** [comment]
🎉

<img width="371" alt="image" src="https://github.com/user-attachments/assets/febca5f4-b79f-4176-b15a-fee5ff47518e">

Looks like this can be closed now.
