### ISSUE TITLE
Walkthrough gets stuck after "delete point" step

### ISSUE THREAD

**Issue by SergeiPatiakin** [openstreetmap/iD#11437]
### How to reproduce the issue?

- Register as a new user
- Start the walkthrough for iD. Follow the instructions without skipping any steps
- In the Points section, follow the instructions for the "delete point" step

### Expected Behavior
- After successfully deleting a point, iD should provide instructions for the next step

### Observed Behavior
- After successfully deleting a point, iD provides no instructions

### Screenshot(s) or anything else?

<img width="1506" height="740" alt="Image" src="https://github.com/user-attachments/assets/15a18d95-40d0-4721-8824-3ee1b51fe20a" />

### Which deployed environments do you see the issue in?

Released version at openstreetmap.org/edit

### What version numbers does this issue effect?

2.36.0

### Which browsers are you seeing this problem on?

Chrome

**Comment by tyrasd** [comment]
fixed by #11442

**Comment by clorofolle** [comment]
I am having the same exact bug still. I've tried both Firefox and Chrome. 
Should I open a new issue? The issue is completely the same as the one described here. 
The only difference in my case is that the language is set to "Italian".
The editor is still version 2.36.0, but I saw the bugfix was deployed?
Thank you.

<img width="2986" height="1500" alt="Image" src="https://github.com/user-attachments/assets/0c4b7f79-c065-40f8-a589-ad19e186048b" />

**Comment by tyrasd** [comment]
The bugfix was not yet rolled out to the osm.org website. This will happen with v2.37 in the coming days. Sorry for the delay. :bow:
