### ISSUE TITLE
Long-clicking doesn't allow moving a node if something was previously selected

### ISSUE THREAD

**Issue by ignaciolep** [openstreetmap/iD#7826]
#### Issue description

With nothing selected, after long-clicking a node until the edit menu appears, it still allows to move it as expected. BUT, if _anything_ was already selected, after long-clicking a node, it doesn't allow to move it.

#### Steps to reproduce the issue

1. Select anything
2. Do a long-click over a node (until edit menu is shown).
3. Try to move the node

#### What's the expected result?

It should allow to move the node.

#### What's the actual result?

It doesn't allow to move the node.

**Comment by tkansgar** [comment]
Hi,
I just wanted to post the same issue and found this one.
I found out, if you press the left button on a node of a selected line (e.g. some kind of highway) and immediately begin to drag it, this is possible (moving of the node begins). But if you wait too long (about 0.3 seconds or so), the selection of the line disappears and the popup menu for node modification appears instead (which formerly only apperared on right click and provides no possiblity to move the node). So moving the node isn't possible in this state. Since nodes of highways aren't visible, if neither the highway nor the node are selected, I couldn't use the way of ignaciolep to move a highway node. The only possible way for me is to begin the drag operation immediately (less than about 0.3 seconds) after pressing the left mouse button on the node. My issue with this is, that I normally use the click lock feature of the mouse driver allowing to begin drag operations by holding down the left mouse button a short (adjustable) time and then releasing it again. So normally I can drag objects without holding down the button. The drag operation is ended by a simple click at the desired end position. But with the current ID version this doesn't work, because the node popup menu appears substituting the selection of the highway or the node, before the drag operation is started by the mouse driver.

**Please, please, please give us back the possibility to move nodes in the easy way like before!**

BR
tkansgar

**Comment by quincylvania** [comment]
@tkansgar Sorry this is causing such big issues for you! As you can see, this is a bug with the new release and we'll fix it soon. I wasn't aware of click locking, but will keep this workflow in mind for future development.

For the time being you can use a slightly older of iD [here](https://preview.ideditor.com/release/) if that helps.

**Comment by tkansgar** [comment]
Hi, is it possible to use the older ID version from within www.openstreetmap.org? There I have an URL like this:
https://www.openstreetmap.org/edit?gpx=3360169#map=20/52.34064/9.22462 (to see one of my uploaded gpx tracks)
So I modified your URL as follows:
https://preview.ideditor.com/release/#background=EsriWorldImageryClarity&disable_features=boundaries&map=20/52.34064/9.22462 (to see the same map area on my desired background with the older ID).
But I don't see my gpx here, and I'm not logged in to www.openstreetmap.org here. So, is it possible to combine parts of both URLs in some way, so that I can use my openstreetmap account and see my gpx?

**Comment by tkansgar** [comment]
Hi again,

a cautious question: is there a possibility to say, when this bug will be fixed and the fixed version will be available at www.openstreetmap.org?

BR
tkansgar

**Comment by quincylvania** [comment]
> But I don't see my gpx here, and I'm not logged in to www.openstreetmap.org here. So, is it possible to combine parts of both URLs in some way, so that I can use my openstreetmap account and see my gpx?

@tkansgar I'm not sure if there's an easy way to view a single uploaded track or not. If you have the GPX file you can simply drag it onto iD from your computer or use the Custom Map Data layer.

> a cautious question: is there a possibility to say, when this bug will be fixed and the fixed version will be available at www.openstreetmap.org?

Unfortunately I can't say for sure. I'm not working on iD full-time right now. I'll fix it as soon as my position returns or I find some spare time. It's an important bug. I'd also welcome a fix from another contributor, but it's a pretty advanced bug.

**Comment by tkansgar** [comment]
I found the possibility to upload a gpx file or to specify an URL to it. The URL of my file at www.openstreetmap.org didn't work (nothing happened, don't know why), but the upload did it. Now I can see again my track in the older iD version, and don't need to display it in the new version started by www.openstreetmap.org in another browser tab. Many thanks for this useful tip! Now I can good live with this interim solution.

**Comment by quincylvania** [comment]
This took some time to debug but it looks like it's fixed with a one line change! So goes web development 😆

**Comment by tkansgar** [comment]
Hi Quincy,

I still have an issue with this. Moving a node now is possible again when using the click lock feature. But each time, I move the whole map scene a little bit by pressing and dragging some point beyond any map object, the selection of the object recently selected (mostly some kind of highway / track) is lost. So I must reselect it after each map scene moving. Is it possible to preserve the selection in this case (like older Id versions did)?

BR
tkansgar

**Comment by quincylvania** [comment]
@tkansgar Hmm could you open a new issue for this? Sounds like a somewhat different problem.

**Comment by tkansgar** [comment]
Just done. Here it is: https://github.com/openstreetmap/iD/issues/8105

**Comment by quincylvania** [comment]
@tkansgar Thanks!
