### ISSUE TITLE
Remember last used imagery

### ISSUE THREAD

**Issue by AntMadeira** [openstreetmap/iD#8665]
Everytime I open iD, the imagery is set to default, although it wasn't always like this.
Is it possible to allow iD to load the last used imagery?

**Comment by boothym** [comment]
For me, iD always loads the last imagery used - even if I was previously editing with country-specific imagery.

So I would suggest that if it's not remembering it for you, there could be an issue with cookies or something?

**Comment by tordans** [comment]
For me, this works on the staging version https://ideditor-release.netlify.app/#background=Berlin-2021&disable_features=boundaries&id=n240109189&map=20.00/52.51704/13.38886  but not on the embedded iD Editor on OSM.org.

I addressed this in https://github.com/openstreetmap/openstreetmap-website/issues/3031 because I thought I remembered that this worked before but apparently it never did for the embedded iD(?)

**Comment by AntMadeira** [comment]
Well, I have cookies allowed and the openstreetmap.org domain without restrains (even for being able to use Mappilary imagery in Firefox), but this issue still remains. This didn't happen in the last 3 years, only since some recent update of iD.

For example, if I'm in edit mode and I open another edit mode from the "Edit" button, the second tab will open the default satellite layer, not the one I'm working on, which is most annoying...


> 
> For me, iD always loads the last imagery used - even if I was previously editing with country-specific imagery.
> 
> So I would suggest that if it's not remembering it for you, there could be an issue with cookies or something?

**Comment by boothym** [comment]
> For example, if I'm in edit mode and I open another edit mode from the "Edit" button, the second tab will open the default satellite layer, not the one I'm working on, which is most annoying...

I've just tried that - and it works correctly for me, remembering the layer from before.

**Comment by AntMadeira** [comment]
Here's the behaviour with Firefox and Chrome. Both show the same problem.

https://user-images.githubusercontent.com/34066528/141839091-650d5824-5eac-4f6b-91f6-b092a710ac91.mp4

https://user-images.githubusercontent.com/34066528/141839133-9c5c345f-95da-4759-9eb5-d3356ba17d64.mp4

**Comment by boothym** [comment]
Ok so I've just tried it in Portugal and I now I have the same problem as you. I think it must be due to the best known imagery at the top of the list with the star.

Can you try it in the UK - where there should be no preferred imagery - to see what happens?

**Comment by AntMadeira** [comment]
Yup, that's it! In the UK, iD remembers the last layer used. And it makes sense, since it was after the introduction of the preferred layer that this started to happen.

I think we nailed this bug.

**Comment by boothym** [comment]
Not quite - it works fine in Ireland and Romania as well. 😄 But those countries do not have "best imagery" in the list, unlike Portugal and Spain.

**Comment by AntMadeira** [comment]
Well, that points to what I was referring above: countries with a preferred imagery don't allow to remember the last used layer.

**Comment by tyrasd** [comment]
see https://github.com/openstreetmap/iD/pull/8914#issuecomment-1189369290
