### ISSUE TITLE
Text mode editing for Tags does not work with iD 2.26.1

### ISSUE THREAD

**Issue by DujaOSM** [openstreetmap/iD#9774]
### How to reproduce the issue?

1. Switch the tag list to text mode
2. Select any object on the map
3. Observe the tag list contents

Nothing happens, i.e. it is empty (although it does accept input, but it still does not change with selection). This is a horrible regression introduced in 2.26.0 or 2.26.1, so much I'd prefer it rolled back until fixed, since it makes any work with tags extremely cumbersome. 

### Screenshot(s) or anything else?

![TagsBox](https://github.com/openstreetmap/iD/assets/48584318/9bc2e233-b6d4-472c-93b4-90fc1d16ef34)

### What version numbers does this issue effect?

2.26.1 (perhaps 2.26.0)

### Which browsers are you seeing this problem on?

Firefox

**Comment by k-yle** [comment]
This was fixed in #9766

**Comment by florinbuzec** [comment]
still not working, no tags showed after clicking on Text button


![Screenshot_173](https://github.com/openstreetmap/iD/assets/108538975/606bbd9f-be1b-4887-93ac-55ccee7e71e8)

**Comment by tyrasd** [comment]
the fix has been deployed on osm.org by now. please try refreshing your browser (the updated version shows version `2.26.2` in the bottom right corner).
