### ISSUE TITLE
ID on Safari 16.6/Mac (M2 Pro) not allowing fiueld entry

### ISSUE THREAD

**Issue by OlneyMe** [openstreetmap/iD#9848]
### URL

https://www.openstreetmap.org/#map=19/52.15344/-0.70146

### How to reproduce the issue?

Safari 16.6 on both an M2 Pro Mac mini and an otherwise identical Intel Mac Mini, running Mac OS Ventura 13.5.

- Click edit and enter deets if necessary;
- You can change the way or node type ( say change one store chain to another - that is, stuff via lookups;
- However, no fields can be selected - ie the cursor cannot be placed, either in the form or under the Tags section;
- Attempting to save changes leads to an Changes description field that will allow a few letters to be typed before jumping to the Sources box, meaning no sensible description can be entered for the change set.

Firefox works as expected.

Someone on the OSM Community forums said that the newest version of ID was pushed 6 hours ago and this problem appeared since them. Have been editing heavily for a couple of weeks with zero issues. The issue is also present in the dev version (2.28.0-dev)

### Which deployed environments do you see the issue in?

Released version at openstreetmap.org/edit

### What version numbers does this issue effect?

2.27.0 - also present in 2.28.0-dev

### Which browsers are you seeing this problem on?

Safari

**Comment by habi** [comment]
This happens to me, too (Safari Version 16.5.2 (18615.2.9.11.10), on MacOS 13.4.1 (c) (22F770820d)), on an 2018 Intel MacBook Pro.

Here's a screen recording of my trying to add a node somewhere randomly...

https://github.com/openstreetmap/iD/assets/1651235/f35bf53e-fce9-4ad1-b810-6d9137c63cfd

**Comment by tyrasd** [comment]
This bug should be fixed in the patch release [`v2.27.1`](https://github.com/openstreetmap/iD/blob/develop/CHANGELOG.md#2271). :bow:

**Comment by OlneyMe** [comment]
> This bug should be fixed in the patch release [`v2.27.1`](https://github.com/openstreetmap/iD/blob/develop/CHANGELOG.md#2271). 🙇

Roughly how long do these taken to bet pushed out? Still seeing 2.27.0

**Comment by danieldegroot2** [comment]
> > This bug should be fixed in the patch release [`v2.27.1`](https://github.com/openstreetmap/iD/blob/develop/CHANGELOG.md#2271). 🙇
> 
> Roughly how long do these taken to bet pushed out? Still seeing 2.27.0

They still have to be merged into applications using iD, For the openstreetmap.org website it usually takes up to 24 hours, otherwise up to a week or longer. This specific patch was pushed a bit late so will likely be merged later today instead. The project runs on volunteer time though.

**Comment by OlneyMe** [comment]
Cool. Many thanks.
